/* xHow do you define an event handler in React?

You define an event handler as a method on the 
component class, just like the render method. 
Almost all functions that you define in React 
will be defined in this way, as methods in a 
class. 

An event listener object listens for specific 
types of events generated by event sources in 
a program. An event handler is a method that 
is called in response to a particular type of 
event. Example below: */

class Talker extends React.Component {
  // define eventhandlers inside their respective classes
  talk() {
      let speech = '';
      for (let i = 0; i < 10000; i++) {
        speech += 'blah ';
      }
      alert(speech);
  }

  render() {
    return <Button />;
  }
}


// To receive the event handler as a prop, do:
export class Button extends React.Component {
  render() {
    return (
      <button onClick={this.props.talk}>
        Click me!
      </button>
    );
  }
}